[package]
name = "astra-emu-minori"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["rlib", "cdylib"]
doctest = false

[features]
default = []
dynamic-plugin-export = []

[dependencies]
abi_stable.workspace = true
astra-core = { path = "../../../../Engine/Source/Runtime/astra-core" }
astra-byte-source = { path = "../../../../Engine/Source/Runtime/astra-byte-source" }
astra-emu-family-api = { path = "../../FamilyApi/astra-emu-family-api" }
astra-emu-family-core = { path = "../../FamilyCore/astra-emu-family-core" }
astra-emu-family-support = { path = "../../FamilySupport/astra-emu-family-support" }
blowfish.workspace = true
crc32fast = "1.5"
directories.workspace = true
encoding_rs.workspace = true
flate2.workspace = true
image.workspace = true
lru.workspace = true
postcard.workspace = true
rc4.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true

[build-dependencies]
astra-emu-family-api = { path = "../../FamilyApi/astra-emu-family-api" }
serde_json.workspace = true
sha2.workspace = true
