pub const ANDROID_INVALID_LIFECYCLE: &str = "ASTRA_ANDROID_INVALID_LIFECYCLE";
pub const ANDROID_WINDOW_ALREADY_CREATED: &str = "ASTRA_ANDROID_WINDOW_ALREADY_CREATED";
pub const ANDROID_SURFACE_UNAVAILABLE: &str = "ASTRA_ANDROID_SURFACE_UNAVAILABLE";
pub const ANDROID_AUDIO_BACKEND_MISMATCH: &str = "ASTRA_ANDROID_AUDIO_BACKEND_MISMATCH";
pub const ANDROID_JIT_FORBIDDEN: &str = "ASTRA_ANDROID_JIT_FORBIDDEN";
pub const ANDROID_RESOURCE_LEAK: &str = "ASTRA_ANDROID_RESOURCE_LEAK";
pub const ANDROID_BUNDLE_IDENTITY_MISMATCH: &str = "ASTRA_ANDROID_BUNDLE_IDENTITY_MISMATCH";
pub const ANDROID_SAF_PERMISSION_REQUIRED: &str = "ASTRA_ANDROID_SAF_PERMISSION_REQUIRED";
