[package]
name = "astra-emu-siglus"
version.workspace = true
edition.workspace = true
license = "MPL-2.0"

[lib]
crate-type = ["rlib", "cdylib"]
doctest = false

[dependencies]
abi_stable.workspace = true
astra-emu-family-api = { path = "../../FamilyApi/astra-emu-family-api" }
siglus_scene_vm = { path = "../../../ThirdParty/siglus_rs/crates/siglus_scene_vm", features = ["astra-hosted"] }
tracing.workspace = true
anyhow = "1"
pollster = "0.3"

[dev-dependencies]
tempfile.workspace = true

[package.metadata.astra]
upstream = "https://github.com/xmoezzz/siglus_rs"
upstream_revision = "e762f9f9c1c94cb490fb13f1367fd06f3e1367b4"
hosted_fork = "https://github.com/2018wzh/siglus_rs"
hosted_fork_branch = "astra-hosted"
hosted_fork_revision = "2ab860f9002f6fd04abce24fdc136bfc5e1a832b"
license_notice = "THIRD_PARTY_NOTICES.md"
modifications = "MODIFICATIONS.md"
