[package]
name = "astra-audio-kira"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
astra-byte-source = { path = "../astra-byte-source" }
astra-platform = { path = "../../Platform/astra-platform" }
kira.workspace = true
schemars.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
rtrb.workspace = true

[dev-dependencies]
astra-headless-test = { path = "../../Developer/astra-headless-test" }

[lib]
doctest = false
