[package]
name = "astra-emu-manager-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
doctest = false

[dependencies]
abi_stable.workspace = true
astra-emu-family-api = { path = "../../FamilyApi/astra-emu-family-api" }
astra-emu-translation-openai-compatible = { path = "../../Providers/astra-emu-translation-openai-compatible" }
rusqlite.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
uuid = { workspace = true, features = ["v4"] }

[dev-dependencies]
tempfile.workspace = true
