[package]
name = "astra-emu-sdk"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
video-ffmpeg = ["dep:astra-media", "astra-media/ffmpeg-vcpkg"]
audio = ["dep:kira", "dep:symphonia"]
default = ["text", "image", "archive", "cache"]
archive = ["dep:astra-core", "dep:astra-byte-source", "dep:serde", "dep:serde_json", "dep:schemars"]
cache = ["dep:astra-core", "dep:lru", "dep:windows"]
text = ["dep:astra-core", "dep:astra-text"]
image = ["dep:image", "dep:lru"]

[dependencies]
tracing.workspace = true
astra-media = { path = "../../../../Engine/Source/Runtime/astra-media", optional = true }
kira = { workspace = true, optional = true }
symphonia = { workspace = true, optional = true }
thiserror.workspace = true
astra-byte-source = { path = "../../../../Engine/Source/Runtime/astra-byte-source", optional = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
schemars = { workspace = true, optional = true }
image = { workspace = true, optional = true }
lru = { workspace = true, optional = true }
astra-core = { path = "../../../../Engine/Source/Runtime/astra-core", optional = true }
astra-media-core = { path = "../../../../Engine/Source/Runtime/astra-media-core" }
astra-text = { path = "../../../../Engine/Source/Runtime/astra-text", optional = true }

[dev-dependencies]
tempfile.workspace = true

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, optional = true, features = ["Win32_Foundation", "Win32_Security", "Win32_Security_Authorization"] }

[[test]]
name = "texture_cache"
required-features = ["image"]

[[test]]
name = "profile"
required-features = ["archive"]

[[test]]
name = "video_worker"
required-features = ["video-ffmpeg"]

[[test]]
name = "video_pcm"
required-features = ["video-ffmpeg"]
