[package]
name = "astra-emu-manager"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[lib]
crate-type = ["rlib"]
doctest = false

[[bin]]
name = "astra-emu-manager"
path = "src/bin_main.rs"

[dependencies]
astra-emu-manager-core = { path = "../astra-emu-manager-core" }
astra-emu-manager-ui-slint = { path = "../astra-emu-manager-ui-slint" }
astra-emu-family-api = { path = "../../FamilyApi/astra-emu-family-api" }
astra-emu-fvp = { path = "../../Families/astra-emu-fvp" }
astra-emu-metadata = { path = "../../Providers/astra-emu-metadata" }
astra-emu-translation-openai-compatible = { path = "../../Providers/astra-emu-translation-openai-compatible" }
astra-observability = { path = "../../../../Engine/Source/Developer/astra-observability" }
abi_stable.workspace = true
cpal.workspace = true
crossbeam-channel.workspace = true
naga.workspace = true
tokio.workspace = true
directories.workspace = true
image.workspace = true
pollster.workspace = true
serde_json.workspace = true
rubato.workspace = true
sha2.workspace = true
slint = { workspace = true, features = ["std", "compat-1-2", "accessibility", "backend-winit", "renderer-femtovg-wgpu", "unstable-wgpu-29", "unstable-winit-030"] }
thiserror.workspace = true
tracing.workspace = true
winit.workspace = true
hassle-rs = "=0.12.0"
wgpu.workspace = true

[target.'cfg(any(target_os = "windows", target_os = "linux", target_os = "macos"))'.dependencies]
gilrs = { workspace = true, features = ["wgi"] }
rfd.workspace = true

[dev-dependencies]
tempfile.workspace = true

[build-dependencies]
sha2.workspace = true
